# Generated by Django 5.2 on 2025-04-19 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENT_INFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('count_meters_flat', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, null=True)),
                ('count_meters_metro', models.IntegerField(blank=True, null=True)),
                ('adress', models.CharField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, null=True)),
                ('tg', models.CharField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('money_zalog', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MESSAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('new_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_flat', models.IntegerField(blank=True, null=True)),
                ('max_flat', models.IntegerField(blank=True, null=True)),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('min_rooms', models.IntegerField(blank=True, null=True)),
                ('max_rooms', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(choices=[('CAO', 'ЦАО'), ('YUAO', 'ЮАО'), ('SAO', 'САО'), ('ZAO', 'ЗАО'), ('VAO', 'ВАО'), ('ANY', 'Не важно')], default='ANY', max_length=4)),
                ('max_metro_distance', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='INFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('count_meters_flat', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, null=True)),
                ('count_meters_metro', models.IntegerField(blank=True, null=True)),
                ('adress', models.CharField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.message')),
            ],
        ),
    ]
