# Generated by Django 5.1.7 on 2025-06-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_contacts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
