# Generated by Django 5.1.7 on 2025-07-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_devclient_info_devmessage_devsubscription_devinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinfo',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.devmessage'),
        ),
    ]
