# Generated by Django 5.1.7 on 2025-08-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_devinfo_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='devmessage',
            name='metro_close',
            field=models.BooleanField(default=False, help_text='True — только до 2000 м от метро; False — не важно'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='metro_close',
            field=models.BooleanField(default=False, help_text='True — только до 2000 м от метро; False — не важно'),
        ),
    ]
